### ISSUE TITLE
Document creation of G Sheets auth files and where they should be saved

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#104]
I have this now. Not sure which are required.

- `./local/client_secret.apps.googleusercontent.com.json`
- `./local/sheets.googleapis.com-python.json`
- `./sheets.googleapis.com-python.json`
- `./tests/sheets.googleapis.com-python.json`

**Comment by turbomam** [comment]
`client_secret_fresh-sheet2linkml.apps.googleusercontent.com.json` shouldn't be mentioned anywhere in the code

**Comment by pkalita-lbl** [comment]
Google Sheets no longer used in pipeline. Closing.
