### ISSUE TITLE
Differences between DH @ GH pages vs NMDC Portal

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#105]
- [x] Users can jump to sections at https://microbiomedata.github.io/DataHarmonizer/main.html?template=dev now, in addition to columns. That's not the case at https://data.dev.microbiomedata.org/submission
- [ ] Blank Globally Unique IDs are allowed at https://data.dev.microbiomedata.org/submission but not at https://microbiomedata.github.io/DataHarmonizer/main.html?template=dev

non difference request:
- [ ] how to make the example data file (https://raw.githubusercontent.com/microbiomedata/DataHarmonizer/master/docs/template/dev/exampleInput/valid_jgi_gen_emsl.tsv) easy to people to obtain?

**Comment by pkalita-lbl** [comment]
Closing as no longer relevant due to how DataHarmoinzer is now integrated into the submission portal.
