### ISSUE TITLE
final steps for section composition, section order and column order

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#107]
review: column ordering is being handled well now (pandas sort over column_order annotations), but no action on section annotation yet

test: all slots claimed by a DH-specifying class (like soil_biosample) should have section and column_order annotations

test: all section values/names assigned to section annotation should be defined in the section order tab
- that's not the case (alpha, beta, etc.)

lower priority test (or design decision): what to do if the column order values aren't exactly 1..(count(slots per section))
- 1,2,4,5
- 1,2,2,3

New functionality:
- assert column-to-section membership based on the section annotation
- sort on the rank of the section also 

DataHarmonizer `data.tsv` row types (see @turbomam's "reunited" etc.)
- section (label only, no parent class)
- column (will have the name of a section in the parent class column)
- permissible value for an enumeration (parent class column = the label of a column)

**Comment by turbomam** [comment]
@sujay, please see [model_sections.py](https://github.com/microbiomedata/DataHarmonizer/blob/issue-110-model-sections/sheet2dataharmonizer/model_sections.py) for the way I want to model DH sections within a LinkML model like `soil_biosample.yaml`, based on the contents of the [Sections_order tab in the Soil-NMDC-Template_Compiled](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1759225432) Google Sheet

**Comment by pkalita-lbl** [comment]
Google Sheets is no longer used the pipeline. If there is still an open issue with column and/or section ordering please open an issue in the `submission-schema` repo.
