### ISSUE TITLE
model DH sections

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#110]
See https://github.com/microbiomedata/DataHarmonizer/issues/107#issuecomment-1027201664

**Comment by turbomam** [comment]
see https://github.com/microbiomedata/DataHarmonizer/blob/issue-110-model-sections/sheet2dataharmonizer/model_sections.py

**Comment by pkalita-lbl** [comment]
I believe this has been superseded by code in the `submission-schema` repo.
