### ISSUE TITLE
section/column annotations should probably go in slot usage

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#115]
If we start building schemas representing multiple DH interfaces (soil, sediment, water, etc.) we might want different section assignment and column ordering for each interface. _Each interface corresponds to one class in the schema, like the current 'soil_biosample'._ In that case, the annotations shouldn't be made on the slots themselves, but rather on slot usage for each interface class.

**Comment by pkalita-lbl** [comment]
This is done
