### ISSUE TITLE
Switch to Google sheet in schemasheets format after GSP

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#127]
As previously discussed, this would move many of the tabs in [Soil-NMDC-Template_Compiled](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=1759225432)  into a single, long, multi-section tab.

Will provide better support for specifying different DH interfaces for different environmental package X user facility X analysis type

**Comment by turbomam** [comment]
See also #128

**Comment by pkalita-lbl** [comment]
Google Sheets is no longer used in the pipeline. Closing.
