### ISSUE TITLE
How will we pre-build different DH interfaces

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#128]
...and make them available for the portal, based on the user's answers to pre-DH questions?

Currently, the `make all` workflow in this repo builds a single `data.tsv`, which is converted to a single `data.js` with the [`make_data.py` code provided by cidgoh/DataHarmonizer](https://github.com/cidgoh/DataHarmonizer/blob/master/script/make_data.py)

Note that Damion at `cidgoh/DataHarmonizer` has a native [LinkML -> JS branch](https://github.com/cidgoh/DataHarmonizer/tree/linkml-datastructure). We should see how its results compare to those generated by our [`sheet2dataharmonizer/converters/linkml2dataharmonizer.py`](https://github.com/microbiomedata/DataHarmonizer/blob/master/sheet2dataharmonizer/converters/linkml2dataharmonizer.py)

**Comment by turbomam** [comment]
Of course there can be multiple different template folders, but only one pre-compiled `main.html` and `main.css`. Maybe this is all moot and I just need to help @brandon understand the mapping from a user's env package/facility/analysis type response to the various template folders in this repo?

**Comment by turbomam** [comment]
But some process could be responsible for creating new template folders and pre-populating them with the required files, beyond `data.tsv`. @sujaypatil96, you and I should review that.

**Comment by pkalita-lbl** [comment]
This is no longer relevant with newer DataHarmonizer infrastructure. Closing.
