### ISSUE TITLE
remove req/rec/opt distinctions in DH sections?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#132]
@mslarae13 please check the interface at https://data.dev.microbiomedata.org/submission/samples

I think you will find that some of the MIxS as-is Required or Recommended columns are colored white, not yellow or magenta, because MIxS doesn't consider them required or recommended for soil samples. 

We could either
- leave the section names as they are which will be informative but not enforced
- move those columns to MIxS modified and assert that they are required or recommended

**Comment by pkalita-lbl** [comment]
I don't think there is any action to do here. If there are slots whose required or recommended status need to be updated, please open an issue in the `submission-schema` repo.
