### ISSUE TITLE
poetry complains about legacy build resources

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#135]
`make all`...

```shell
poetry run range_str_ser \
		--model_file target/soil_biosample_modular.yaml \
		--selected_class soil_biosample \
		--output_file target/soil_biosample_regex_insight.tsv
```
> /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(

Is it because they can be found in the submodule directories?

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
