### ISSUE TITLE
review sets of enums

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#136]
some of the implementation is in hident

- gold paths
- MIxS environmental triad

- some combinations within each set may not be reasonable or legal
- indent with whitespace or underscores?
- if a column is set to select (for enums), then it doesn't seem to tolerate hand-entered values even if the match the regular expression
- make sure alphabetization and indentation are exhaustive. For example if B is an indirect subclass of A, it should still be indented under A (but by how many indentations? May not want to imply that it is a sibling of the direct subclasses.)

---

When to implement annotation? Run as needed and save mapped IDs into SNTC?

**Comment by pkalita-lbl** [comment]
I don't believe there is any specific action here anymore. If there is an issue with the way enums are built please open a new issue in the `submission-schema` repo.
