### ISSUE TITLE
https://data.dev.microbiomedata.org/submission/samples does not allow saving invalid sheets

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#139]
Which could be very useful for communicating unexpected results between users and developers

**Comment by mslarae13** [comment]
Agreed!! This is how people might best communicate if they're having issues... Example, the user send us an email of 'I tried to submit the attached spreadsheet to the portal but DH wouldn't allow me to.. can you upload and see if you can help'
