### ISSUE TITLE
How and where to credit upstream DH developers

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#141]
We should mention the [`cidgoh/DataHarmonizer`](https://github.com/cidgoh/DataHarmonizer/graphs/contributors) developers, funders, etc. in our documentation and on the submission portal 

@ddooley

**Comment by ddooley** [comment]
Just pointing to cidgoh/DataHarmonizer and acknowledgement of help from our DH developers is sufficient and appreciated!

**Comment by emileyfadrosh** [comment]
I believe this has been addressed, but please reopen and post additional information if not. Thanks!
