### ISSUE TITLE
Make URLs hyperlinked in the help text

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#149]
for example: http://www.geosamples.org/getigsn in the help text below

![image](https://user-images.githubusercontent.com/7374085/153295563-474177d0-881e-4c9d-bf1e-dacc20f7dce9.png)

**Comment by turbomam** [comment]
Yes, that would be good.

This will require a JavaScript developer. @dehays ? @subdavis ? @sujaypatil96 ?

Otherwise punt to Damion for him to fit into his queue.

**Comment by pkalita-lbl** [comment]
This is done now. Closing.
