### ISSUE TITLE
All MIxS required terms should be required and highlighted yellow

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#150]
According to MIxS, these terms should be required:
- Geographic location
- Geographic location (latitude and longitude)

In the interface, they currently are not highlighted yellow nor required (validates successfully if these cells are empty)
![image](https://user-images.githubusercontent.com/7374085/153296766-8c40c9c6-f9c4-412f-b1c8-2a7d35342082.png)

**Comment by turbomam** [comment]
Agreed. Solution may be complex. See #151

**Comment by pvangay** [comment]
In the latest version of https://data.dev.microbiomedata.org/submission/samples

Geographic location and Geographic location (latitude and longitude) moved from MIxS to Mixs modified. I dont understand why. @turbomam

**Comment by pkalita-lbl** [comment]
This is fixed now. Closing.
