### ISSUE TITLE
All "MIxS required where applicable" terms should be highlighted purple (recommended)

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#151]
Based on my understanding of "required where applicable", I would expect these terms to be highlighted in purple to indicate that they are recommended terms.

![image](https://user-images.githubusercontent.com/7374085/153297284-e3e61f88-99bc-4928-8dc3-f10f9578fa8d.png)

**Comment by turbomam** [comment]
Agreed.

If a term is taken from MIxs or NMDC as-is, that authority determines whether the corresponding column is recommended or required. That's completely independent of which DH section it is assigned to.

When there's a MIxS term in a recommended or required Section with the wrong color (and therefore the wrong validation rule), the current alternatives are:
- statically remodel all attributes of the term, including revised recommended and required flags, in the MIxS modified tab. That static remodelling runs the risk of getting out of sync with the living MIxS standard.
- petition GSC to change the requirement status in the MIxS standard and wait for their response
- I have been meaning to implement a minimal-modification strategy as part of moving from the existing SNTC Google sheet to the [schemasheets](https://github.com/linkml/schemasheets) standard, but I don't see how that could be completed in the next week or two.

I think therese some additional documentation and discussion about this out there. I'll try to link it in tomorrow.

See also #150

**Comment by pvangay** [comment]
After reading this, I believe I am uninformed about the logic that determines when terms are labeled with "recommended". 

These are how terms are labeled with checklist requirements from MIxS: 

- mandatory (M)
- conditional mandatory (C)
- optional (X)
- environment-dependent (E)
- not applicable (-) 

Is our section "MIxS required where applicable" equivalent to terms marked "conditional mandatory (C)" in MIxS? 

It looks like there are no as-is MIxS terms marked "recommended" so perhaps that means that there is no mapping between DH's "recommended" and MIxS's checklist requirement categories. I'd like to understand this better.

**Comment by pkalita-lbl** [comment]
I don't know if there is any specific actionable item here. If any specific slot needs have its recommended or required status changed, please open an issues in the `submission-schema` repo. Closing.
