### ISSUE TITLE
Fix typos in term descriptions

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#154]
### Environmental package description
"environemtn" should be "environment"
### DNA Seq Project ID, DNA Sample ID, and DNA Seq Project Name descriptions
"vales" should be "values"

**Comment by turbomam** [comment]
While we're at it... @mslarae13 are you OK with my shortened definition on `environmental package`? The one provided by MIxS is terrible. I think I left a comment on cells like this where I made a change.

**Comment by turbomam** [comment]
Typos fixed, including the presence of 'vales' in analogous `RNA...` columns. Not published yet.

**Comment by mslarae13** [comment]
> While we're at it... @mslarae13 are you OK with my shortened definition on `environmental package`? The one provided by MIxS is terrible. I think I left a comment on cells like this where I made a change.

I just checked the google sheet. I'm good with your definition. That was from MIxS v5
