### ISSUE TITLE
Provide more detail in "Volume in uL" description

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#155]
Values < 25 requires special permission. Can we have more specific instructions for users? e.g. should they contact their assigned JGI Project Manager?
![image](https://user-images.githubusercontent.com/7374085/153307088-611178e3-7bdf-43b7-a760-6e1c9955f6d9.png)

**Comment by dehays** [comment]
@pvangay Yes, permission would need to come from the JGI project manager.
