### ISSUE TITLE
Consider if "DNA Collection Site" is redundant and remove

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#156]
Based on the [JGI template](https://docs.google.com/spreadsheets/d/1kcfAyT_gqjduVGi3QCAJMi0rICsscXA2/edit?usp=sharing&ouid=103200190401406769935&rtpof=true&sd=true), the help states: "Provide information on the specific tissue type or growth conditions." 

This term feels redundant and I think this can be derived from other terms we already collect (we should reduce the repetitive information that the user has to enter). For example, for soil, we could fill this in with values from "growth facility" and "storage conditions". 

If @dehays @mslarae13 agree, we could remove this from the DH interface.

**Comment by ssarrafan** [comment]
@pvangay is this still an issue that needs to be resolved? I'm removing David from this but if should be assigned to someone else besides Montana let me know.

**Comment by pvangay** [comment]
Feels like David is still probably the best person to comment on this since he's working on the mapping for JGI terms?

**Comment by mslarae13** [comment]
Looking at the example for "DNA collection site" they have "untreated pond water" this seems really similar to "sample isolated from" in the context of environmental samples.
Because it's growth conditions, I think if we were doing cultures it would be very different. But overall, I agree & unless @dehays  sees an issue with calling them the same, in relation to NMDC environmental samples, we can probable map it to a different term.

**Comment by ssarrafan** [comment]
Adding to sprint based on subport squad task list. FYI @mslarae13

**Comment by mslarae13** [comment]
@turbomam curious on your thoughts here as we're adding a "Site".
Site in the context of the JGI template means "pond water" or "peat bog" a general way of describing the site. 
We could probably remove this and use whatever someone puts into "environmental medium"

I honestly don't know. I understand Pajau's point that it's repetitive, but it's a GOLD/JGI slot. SO I hesitate to make a change and risk no adhering to their requirements.

@emileyfadrosh & @aclum  also interested in your thoughts on this. Should we just map it to another column & remove it? Or keep it & deal with the redundancy.

**Comment by mslarae13** [comment]
@ssarrafan overdue, please add to January 2023 sprint

**Comment by aclum** [comment]
@emileyfadrosh  wants to keep all JGI terms for now.

**Comment by turbomam** [comment]
I think part of our responsibility is to normalize 3rd party terms into a smaller number of NMDC terms and explicitly state which 3rd party terms ours map too.

@emileyfadrosh do you literally mean that all terms used by our partners should be kept as-is, even if they have the same semantics as some other 3rd party term, or an existing NMDC term? We don't have `emsl_depth` and `jgi_depth` terms.

As opposed to committing to gathering all of the datatypes the partner needs, even if their label doesn't appear anywhere on the data collection form (DH/submission portal)

**Comment by ssarrafan** [comment]
@turbomam @emileyfadrosh @mslarae13 @aclum  can we consider this done per Emiley's comment from Alicia?

**Comment by aclum** [comment]
I think we wanted to bring this up at the weekly sync but there was not
time last week and there is no meeting this week.

**Comment by ssarrafan** [comment]
@emileyfadrosh this needs to be discussed with you. I'm adding this to the agenda for the sync on Feb 8th when you're back.
FYI @aclum 
Moving to the next sprint

**Comment by mslarae13** [comment]
Marking this as "in review" as it's pending a larger discussion

**Comment by mslarae13** [comment]
@ssarrafan  we never got to discuss this at sync. I'm meeting with Emiley on 02/13 & I'll bring it up there.

**Comment by ssarrafan** [comment]
@emileyfadrosh this issue needs feedback from you and was determined to be a blocker at the squad leads meeting today.  Can you please weigh in on this when you're back.

**Comment by ssarrafan** [comment]
Moving this to the current sprint for review from @emileyfadrosh

**Comment by mslarae13** [comment]
Emiley will check with Tjiana and Alicia if it's required for the sample types we have. If not, then non-issue remove. If it is required, we need to leave it as is for JGI requirments

**Comment by emileyfadrosh** [comment]
This term should be dropped as it is optional for metagenomes since there is no asterisk. The [help link](https://projects.jgi.doe.gov/metadata/collaborator_samples/help) confirms this, the field is required for RNA or methylation but not environmental samples.

Thanks @aclum. 

@turbomam @mslarae13 @ssarrafan -- can this be easily removed from the schema? Thanks.

**Comment by mslarae13** [comment]
Thanks!! That help link is "Forbidden" for me, so I can't see it ... but anyway

@turbomam ... let's remove "dna_collect_site" & "rna_collect_site" from the schema. I believe these are in the jgi.yaml file

Based on Alicia's comment below, dna_organisms & rna_organisms can also be removed

"dna_organisms" ..."Known / Suspected Organisms" in the JGI template also does not have an * ... does that mean it can be removed @aclum ?

**Comment by aclum** [comment]
@mslarae13 "Known / Suspected Organisms" is not a required field for metagenomes for JGI

**Comment by mslarae13** [comment]
Will continue into next sprint meeting with Mark and Patrick to hopefully get a plan to wrap this up (03/08)

**Comment by ssarrafan** [comment]
@turbomam @pkalita-lbl any update on this? Still active? Move to post-GSP?  Move to next sprint?

**Comment by pkalita-lbl** [comment]
Sorry I don't know. It hasn't been on my plate.

**Comment by ssarrafan** [comment]
@mslarae13 can you determine if this is still high priority or if it can wait till post GSP? I'm removing from sprint and adding the backlog label for now.

**Comment by turbomam** [comment]
This is easy. I'll do it now.

**Comment by turbomam** [comment]
slots currently in the schema with "organism" in the name/title
-   dna_organisms/DNA expected organisms
-   rna_organisms:/RNA expected organisms
-   organism_count/organism count

slots with 'site' in the name/title
- dna_collect_site
- rna_collect_site

I am going to de-associate the following slots from all submission schema classes. That means they won't appear in the DH interfaces.
-   dna_organisms/DNA expected organisms
-   rna_organisms:/RNA expected organisms
- dna_collect_site
- rna_collect_site

I will leave them defined in the schema.

**Comment by turbomam** [comment]
I apologize for dragging my feet so long with this issues and others like it.

Here are some things we can all do to make it easier to act on issues requiring changes to the nmdc-schema and the submission schema, for as long at that remains a separate resource.

1. include very focused tasks in the first post in the issue. If it requires some discussion, it's OK to edit the first post and add the tasks in later.
2. the tasks should refer to the slots by their slot names or tiles, exactly as they appear in the schema. If there's a need to refer to them by some other terms, then we should add those terms to the schema. In that case, please provide a link to a document where I can see the desired alias _in situ_. Once aliases are added, please refer to the slots by names, titles or aliases, exactly as they appear in the schema.
3. please provide valid and invalid data to illustrate the change you want

I am 100% committed to helping us succeed with those policies and will help in any way I can.

**Comment by ssarrafan** [comment]
> I apologize for dragging my feet so long with this issues and others like it.
> 
> Here are some things we can all do to make it easier to act on issues requiring changes to the nmdc-schema and the submission schema, for as long at that remains a separate resource.
> 
> 1. include very focused tasks in the first post in the issue. If it requires some discussion, it's OK to edit the first post and add the tasks in later.
> 2. the tasks should refer to the slots by their slot names or tiles, exactly as they appear in the schema. If there's a need to refer to them by some other terms, then we should add those terms to the schema. In that case, please provide a link to a document where I can see the desired alias _in situ_. Once aliases are added, please refer to the slots by names, titles or aliases, exactly as they appear in the schema.
> 3. please provide valid and invalid data to illustrate the change you want
> 
> I am 100% committed to helping us succeed with those policies and will help in any way I can.

@turbomam Would it make sense to create a template for schema related feature requests?  Also, as requested last week I'm adding this to the Wed sync this week.

**Comment by turbomam** [comment]
> @turbomam Would it make sense to create a template for schema related feature requests? Also, as requested last week I'm adding this to the Wed sync this week.

Will add to submission schema repo and link here
