### ISSUE TITLE
"Depth, meters" should be a required field

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#159]
Depth is required for soil - should be marked yellow and should fail on validation if the cells are empty. Currently, validates successfully even if the cell is empty.

**Comment by turbomam** [comment]
see [`depth, meters`](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=770915920&range=10:10)

column names are case sensitive

**Comment by turbomam** [comment]
updated. will test.

**Comment by pvangay** [comment]
sorry about changing the cases - when Julia and I jotted down our findings in google docs initially, it autoconverted some letters if it was at the start of a sentence. will be more aware of this next time

**Comment by turbomam** [comment]
> autoconverted some letters if it was at the start of a sentence

Ah, I can see that.

**Comment by turbomam** [comment]
I think you'll find that the column header is yellow now and that empty cells in the column fail validation, but I haven't changed which section it goes it.

**Comment by pvangay** [comment]
this is fixed.
