### ISSUE TITLE
Rules for editing Soil-NMDC-Template_Compiled?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#16]
[Soil-NMDC-Template_Compiled](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=0) is the input into this repo's pipeline for building DataHarmonizer [data.tsv](template/dev/data.tsv) templates, so it can't be edited in a completely open-ended way.

Some technical or policy solution should be developed so that the author(s) (@mslarae13) of Soil-NMDC-Template_Compiled are enabled to make corrections and improvements.

**Comment by turbomam** [comment]
See also #6

**Comment by pkalita-lbl** [comment]
Google Sheets no longer used in the pipeline.
