### ISSUE TITLE
Add validation rules for DNA Container Label

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#161]
Currently the guidance for DNA Container Labels states that the values must be unique and less than 20 characters. There appears to be no validation for this term because values > 20 characters or duplicate values validate just fine.

![image](https://user-images.githubusercontent.com/7374085/153315227-a30faeaf-3a0b-48e6-8927-c84d971a4596.png)

**Comment by turbomam** [comment]
Remove "<20 characters" from the guidance (implemented as a LinkML comment) or add tighter validation?

Proposed new SNTC `syntax` ie LinkML [string_serialization](https://linkml.io/linkml-model/docs/string_serialization/#slot-string_serialization): `{text < 20 characters}`, which would become a regular expression or LinkML [pattern](https://linkml.io/linkml-model/docs/pattern/) of `^.{1,20}$`

See also https://github.com/linkml/linkml/issues/176

**Comment by pkalita-lbl** [comment]
This appears to be fixed now. A plate name longer than 20 characters fails validation. Closing.
