### ISSUE TITLE
Update JGI terms that should not be required

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#162]
These 3 terms should not be required according to the [JGI template](https://docs.google.com/spreadsheets/d/1kcfAyT_gqjduVGi3QCAJMi0rICsscXA2/edit?usp=sharing&ouid=103200190401406769935&rtpof=true&sd=true
). They're currently marked yellow and fail on validation if left empty.

- DNA Absorbance 260/230
- DNA Absorbance 260/280
- DNA Expected Organisms

**Comment by turbomam** [comment]
I demoted these to recommended but can revert or change to blank (meaning entirely optional) based on further feedback.

**Comment by turbomam** [comment]
@mslarae13 @pvangay is `RNA Expected Organisms` required, recommended or optional?

**Comment by turbomam** [comment]
@mslarae13 @pvangay @cmungall 

pet peeve alert:

The descriptions for the `xNA Expected Organisms columns`:
> expected to contain microbes (59%) fungi (30%), viruses (10%), tadpoles (1%)

Seems to imply that fungi and viruses are disjoint from microbes. Do we have definitions for those terms in this context? Isn't 'microbe' a synonym for [microorganism](https://en.wikipedia.org/wiki/Microorganism), which can be defined as an organism of microscopic size? That would certainly include all viruses and many fungi.

**Comment by pvangay** [comment]
> @mslarae13 @pvangay is `RNA Expected Organisms` required, recommended or optional?

It's not required on the DNA template, so I suspect it should be the same on the RNA template. I don't see a recommended option for JGI terms in their original template - I would presume this term is optional.

> expected to contain microbes (59%) fungi (30%), viruses (10%), tadpoles (1%)

I think this is in the example (not description) of the JGI template. My guess is they probably meant to say bacteria and probably typed it too quickly. Agree, microbes typically means the superset of the above.

**Comment by mslarae13** [comment]
> >> @mslarae13 @pvangay is `RNA Expected Organisms` required, recommended or optional?
>
>> It's not required on the DNA template, so I suspect it should be the same on the RNA template. I don't see a recommended option for JGI terms in their original template - I would presume this term is optional.
> 
>Agreed, optional. 

> >> expected to contain microbes (59%) fungi (30%), viruses (10%), tadpoles (1%)
> 
>>I think this is in the example (not description) of the JGI template. My guess is they probably meant to say bacteria and probably typed it too quickly. Agree, microbes typically means the superset of the above.
>
>microbes being bacteria or archea or fungi or all is variable... I think we can update this for our template & be more clear, but right now it matches the JGI template so people are more familiar and this is what they'd expect. I don't care either way.
