### ISSUE TITLE
prepopulate "environmental package" based on previous page selection

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#168]
Users should not need to enter in a value for the "environmental package" again if they already selected this in the previous page. This term should be pre-populated or removed entirely (and the value for this term can be inferred and stored based on the selected template).

2nd page
![image](https://user-images.githubusercontent.com/7374085/153321429-ae08f65f-7321-4098-b16d-d2c6b4c8d865.png)

3rd page
![image](https://user-images.githubusercontent.com/7374085/153321450-6972132a-71c1-419b-bbc8-e45dd934156c.png)

**Comment by turbomam** [comment]
Agreed. I can imagine the environmental package value entered during on the  previous study submission pages could be injected into the DH template, or that the environmental package column could be omitted and the value could be injected into the into the data after the user clicks the validate/submit/next page buttons.

Both of those are outside the scope of DH template creation.

**Comment by pkalita-lbl** [comment]
We removed this slot from the submission schema. When submission data is loaded into Mongo, the `env_package` slot (from `nmdc-schema`) is populated automatically. Closing.
