### ISSUE TITLE
DNase not DNAse

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#169]
@mslarae13 I'd like to make that capitalization change throughout SNTC

see https://en.wikipedia.org/wiki/Deoxyribonuclease

**Comment by mslarae13** [comment]
@turbomam what is SNTC?
JGI's template has DNAse so I think we need to leave it like JGI has it. 

Where did you see it should be DNase?

**Comment by mslarae13** [comment]
DNase is conventionally correct. Update NMDC schema to be correct. @sujaypatil96 's work on mapping the terms will them map DNase to DNAse for the JGI export.

**Comment by turbomam** [comment]
SNTC = @turbomam's abbreviation for @mslarae13's  Soil NMDC Terms Compiled google sheet

by the way

**Comment by turbomam** [comment]
Implement this in sheets_and_friends and/or `jgi_mg.yaml` etc.

**Comment by mslarae13** [comment]
+ jgi_mt.yaml

Mark will make the update.. some of the titles have DNase written correctly, but it's wrong in some of the comments. check and update for consistent use as DNase

**Comment by turbomam** [comment]
Schema files updated. Will check sheets_and_friends now.
