### ISSUE TITLE
Run make_data script over dev template following changes to main.css, main.js, etc.

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#17]
For example, now that @subdavis committed #15 

Make a backup?

[script/make_data.py](script/make_data.py)

[dev/data.tsv](dev/data.tsv)

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
