### ISSUE TITLE
Need clarity on available DH templates

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#172]
Selecting all omic types from the [multiomics page](https://data.dev.microbiomedata.org/submission/multiomics) 
![image](https://user-images.githubusercontent.com/7374085/154130268-6e229f01-fd7a-4afa-84bc-e27c132bdd85.png)

I only see JGI metagenomics on the DH template, and no other JGI omics sections.
![image](https://user-images.githubusercontent.com/7374085/154130669-a280974d-0eaa-4bd8-b100-44e520a99767.png)

Is this the only template available right now? It's fine if it is, I just need to know what to demo.

**Comment by turbomam** [comment]
Yes, we only have a template for soil biosamples, with analyses at EMSL and JGI (for metagenomics). 

I would need a little work to test the generation of other interfaces, but I think the framework is in place. (The configuration might get a little verbose/repetitive. I need to work on that.)

More so, subject matter experts would need to determine what columns to include in any other interface, and whether any of their attributes would deviate from soil_emls_jgi_mg column attributes.

**Comment by pvangay** [comment]
Great thanks. Much appreciated!
