### ISSUE TITLE
lifecycle of modified DH JS files

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#175]
see aso #174 

for @subdavis

**Comment by turbomam** [comment]
I copied https://github.com/microbiomedata/DataHarmonizer/blob/submission-portal-3/script/main.js

from https://github.com/microbiomedata/DataHarmonizer/commit/a16d10c3d43414c1c2c0e5cd60265a6ff2dfd406

into https://github.com/microbiomedata/sheets_and_friends/blob/main/artifacts/for_data_harmonizer_scripts/main.js

**Comment by turbomam** [comment]
Note that I changed the default template in https://github.com/microbiomedata/sheets_and_friends/commit/2fbf37d7e37ade1d32f2b09b52bcce33a55b959e

That's so people opening the DH interface outside of the portal (eg in GH pages) will land on the intended template.

**Comment by turbomam** [comment]
See https://github.com/microbiomedata/DataHarmonizer/pull/146#issuecomment-1043145645

**Comment by subdavis** [comment]
Thanks, I'm now making changes to the correct file in sheets_and_friends.
