### ISSUE TITLE
Using submodules to ensure availability of mixs-source and nmdc-schema YAML files

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#2]

**Comment by turbomam** [comment]
When cloning this repo, one must run two commands: git submodule init to initialize your local configuration file, and git submodule update to fetch all the data from that project and check out the appropriate commit listed in your superproject

- [x] Put in Makefile

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by turbomam** [comment]
THe post init submodule commands shouldn't be run on every make all. That will detach the branch from the head. Both submodules should always be on the main/master branch.

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development, which doesn't use git submodules.
