### ISSUE TITLE
Generate valid MIxS soil + NMDC biosample LinkML based on Soil-NMDC-Template_Compiled

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#21]
**Add EMSL and JGI terms ASAP too**

Related work
- See also #20 
- `make all` already comes close to this but is too inclusive (and the workflow is a mess)
- See also [modular_gd.py](modular_gd.py)

Terms will come from [Soil-NMDC-Template_Compiled](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0)

The result should be a LinkML YAML file that passes basic validation, like serving as the input into `gen-yaml`

Take `slot` terms from the `mixs_packages_x_slots` tab where the `package` column = 'soil' and the `package` column = 'use as-is or 'borrowed'

Take `name` terms from tab `nmdc_biosample_slots` where column `from_schema` != 'https://microbiomedata/schema/mixs'

All of those slots should be assigned to a new class like `soil_biosample`

**Comment by turbomam** [comment]
see also #24

**Comment by turbomam** [comment]
MIxS soil + NMDC biosample **+ EMSL** implemented with `make modular_templating_handoff`, although that name may change. Retired Makefile rules have been commented out.

JGI still pending.

**Comment by turbomam** [comment]
I think this is complete, but we stopped validating with `gen-yaml` because it doesn't seem to like annotations

**Comment by pkalita-lbl** [comment]
Mark indicated this was complete. Closing.
