### ISSUE TITLE
Getting mixs-source submodule from tubomam org

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#3]
My fork removes some of the comments (Occurrence, slot used in packages) as those don't seem helpful in the DataHarmonizer Guidance.

see https://github.com/turbomam/mixs-source/commit/78d1fe9663386332351f5dd08f68844b8ca1adf0

see also #2

**Comment by turbomam** [comment]
Having trouble adding those discarded comments as annotations

**Comment by turbomam** [comment]
the turboman branch should be folded in the GSC org. See https://github.com/turbomam/mixs-source/issues/4

**Comment by pkalita-lbl** [comment]
I believe this issue is about doing development in this fork. Closing in preparation of archiving it. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
