### ISSUE TITLE
Document Google sheets authentication

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#4]
Authentication is required before these scripts (and tests) can access the Soil-NMDC-Template_Compiled Google Sheet. Documentation is required.

This is especially tricky if running tests like `test_sntc.py` if authentication is incomplete. If `local/client_secret.apps.googleusercontent.com.json` is present but `sheets.googleapis.com-python.json` isn't, run it like this the first time around:

```shell
poetry run pytest -s test_sntc.py
```

You will be asked to open a URL, grant authorization to these scripts, and then paste a code back into the shell

**Comment by fabform** [comment]
This is handy to find google sheets id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
