### ISSUE TITLE
regex for {float} ng/uL shouldn't include "ng/uL" etc

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#46]
just validate a bare float

@mslarae13

**Comment by ssarrafan** [comment]
2 hour task per Mark. Would apply to any float type column.  
Bonus after organizing columns. See #59

**Comment by turbomam** [comment]
The `syntax` for 'dna_concentration' etc. in [JGI_sample_slots](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=541445893)  is now just '{float}'. 

See also

@mslarae13 has pointed out the importance of letting submitters know that they must report their concentrations of DNA (etc.) according to a mandated unit. @cmungall, @mslarae13  and I have agreed that those mandated units should appear in each column's header. I haven't done that yet.
