### ISSUE TITLE
DRY about linkml model enrichment in Makefile

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#53]
@cmungall , could you help me try to generalize a pattern for running LME enum annotation over several different enums, in series?

We'll probaly want to tune the `ontology_string`, `max_cosine` and `trim_parentheticals` for each `requested_enum_name`

I do remember your request to separate the annotation from the NMDC DH build

**Comment by turbomam** [comment]
As of now, the enums are 

- analysis_type_enum
- cur_land_use_enum
- dna_cont_type_enum
- dna_dnase_enum
- dna_sample_format_enum
- drainage_class_enum
- env_package_enum
- fao_class_enum
- growth_facility_enum
- oxygen_relationship_enum
- profile_position_enum
- samp_biotic_relationship_enum
- sample_type_enum
- soil_horizon_enum
- storage_condt_enum
- tillage_enum

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
