### ISSUE TITLE
revist deep diff and ast parsing for reconciling same-name LinkML terms (low priority)

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#54]
Currently, most of the methods use here just overwrite terms. We're largely trusting Soil-NMDC-Template_Compiled to not request a slot from two different sources

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
