### ISSUE TITLE
What roles can NMDC DH play in the future?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#56]
Human + API repair enrichment and curation of EMSL, JGI or  KBase data?

Integration with NMDC runtime?

@hubin-keio and @scanon, do you have anything to contribute?

**Comment by hubin-keio** [comment]
My main concerns are DH is going to play with the NMDC run-time API (or other APIs). Now unique sample identifiers are assigned by the NMDC run-time API but without associated sample metadata. Will there be a single authority of truth for sample information across NMDC? And do we have a clear path of linking sample metadata from JGI and EMSL?

**Comment by pkalita-lbl** [comment]
I don't believe there is any actionable task here. Closing.
