### ISSUE TITLE
indent DH enums/pulldowns according to subclass hierarchy

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#58]
see https://github.com/turbomam/hident

**Comment by turbomam** [comment]
see also #57

**Comment by pkalita-lbl** [comment]
There is now [code](https://github.com/microbiomedata/submission-schema/blob/213cc49e528f799a03a1593f92e77dd7ec5d10a7/src/nmdc_submission_schema/datamodel/oak_tree_to_pv_list.py) in `submission-schema` to build indented lists using underscores.
