### ISSUE TITLE
expectations of SNTC from test_sntc.py

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#6]
I need to do a better job of communicating these to @mslarae13 or agreeing on alternatives

Regarding [Soil-NMDC-Template_Compiled](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=0)

- tab name and ordering won't change. 
    - **support for adding new tabs to the left should be added**.
- tab names and order will match the `sheet_name column` in tab `SheetIdentification` 
    - **not implemented yet**
 - no otherwise populated row in the `Terms` tab will have an empty `Column Header `

**Comment by turbomam** [comment]
- as with column `Column Header` in `Terms `, `row_ord ` should never be empty in an otherwise populated row

**Comment by turbomam** [comment]
see `tests/test_sntc.py`

**Comment by pkalita-lbl** [comment]
Closing as we don't manage templates with Google Sheets anymore.
