### ISSUE TITLE
Keep Soil-NMDC-Template_Compiled, esp. SheetIdentification tab tidy and authoritative

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#61]
[SheetIdentification](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=1894635793)

Tests have been started for this task

see also #59 

- all tabs that appear in [Soil-NMDC-Template_Compiled](docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0) must be listed in the `SheetIdentification` tab
- the tabs should (?) be listed in the order they appear in `Soil-NMDC-Template_Compiled`
- tabs that are expected to be parsed in creation of DH templates must be tagged as `input for soil DH template generation` in `SheetIdentification`
- tabs that aren't tagged as to be parsed in creation of DH templates, or don't serve some other well-characterized purpose should be deleted
    - maybe we should designate some tabs as scratch space?

**Comment by turbomam** [comment]
@mslarae13 thanks for the information about tabs that can be deleted. I think I have acted on all of them.

**Comment by pkalita-lbl** [comment]
Google Sheets no longer used in pipeline. Closing.
