### ISSUE TITLE
may need a gsheets authenticating script

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#63]
I moved `test_sntc.py` into `tests/`, and when I next tried to run the test suite (by right clicking on the rest folder in PyCharm), it appeared that a new google sheet authentication step was required

> Please go to this URL and finish the authentication flow

etc., but the test script didn't pause for the next step:

> Enter the authorization code:

I ran this in the PyCharm Python Shell, after `cd`-ing to `tests\`

```python
import pygsheets
sntc_id = '1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0'
client_secret_json = "../local/client_secret.apps.googleusercontent.com.json"
gc = pygsheets.authorize(client_secret=some_google_auth_file)
```

> Please go to this URL and finish the authentication flow: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id...
Enter the authorization code: >? ...

That created a `sheets.googleapis.com-python.json` in `tests/` and the tests continued successfully. Maybe I could have just copied the previously created `sheets.googleapis.com-python.json` from the project root?

Creating a `sheets.googleapis.com-python.json` requires a client secrets file, as defined in  `client_secret_json = "../local/client_secret.apps.googleusercontent.com.json"` above. Neither of those should be checked into GitHub!

**Comment by turbomam** [comment]
And or better documentation about where `sheets.googleapis.com-python.json` and `client_secret*apps.googleusercontent.com.json` need to live

**Comment by pkalita-lbl** [comment]
Google Sheets no longer used in pipeline. Closing.
