### ISSUE TITLE
section-based jump and hide

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#70]
Requesting section-orients navigation in addition to column-based navigation.

Who's in the best position to implement these? Somebody in NMDC, Kitware, or CIDGOH?

Hoping to implement by early February, for a late February conference demo

- [ ] add jump to section
- [ ] add show/hide section

**Comment by ddooley** [comment]
CIDGOH can add that on pretty easily.  About show/hide section, would it make sense that just one section show at a time in that mode?  And that frozen first column always shows, regardless of which section it might be in?

**Comment by turbomam** [comment]
Thanks @ddooley. The jump and show/hide functionality added ~ 2 weeks ago is great, including the frozen first column.

Some of my NMDC colleagues have asked about the potential for showing/hiding arbitrary combinations of sections. For example with checkboxes.

**Comment by ddooley** [comment]
I wondered if that might come up.  That is certainly doable. The checkbox functionality may require breaking out the section list into a separate popup menu, so adding one more click into the process.  Lower priority?

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. If this is still required open an issue in the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer).
