### ISSUE TITLE
report MIxS/SNTC enum differences 

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#75]
## Implementation:
- currently [printing to console in a test](https://github.com/microbiomedata/DataHarmonizer/blob/24e90b4541e639a7872ef5b1d0092925448efe1c/tests/test_sntc.py#L234-L271)
- manually saved a static [report](https://github.com/microbiomedata/DataHarmonizer/blob/master/freezes/mixs_vs_sntc_enums.txt)

## @turbomam's recommendations:
- `cur_land_use`: add the parenthetical portion _(e.g. tulips)_ of `horticultural plants` back in for the sake of consistency. We could revisit whether we want to display "parenthetical portions" at all in the future
- `env_package`: SNTC only has `soil`, so the MIxS only set looks large. Leave as-is.
- `tillage`: the MIxS terms are all lower case. The SNTC `tillage` permissible terms are capitalized, unlike all of the other SNTC permissible terms. Switch to lower case for consistency.

Is that OK with you, @mslarae13 ?

**Comment by turbomam** [comment]
I made the changes I suggested above

**Comment by pkalita-lbl** [comment]
Mark said he made the changes. Closing.
