### ISSUE TITLE
proofreading Soil-NMDC-Template_Compiled

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#77]
I left several comments in [Soil-NMDC-Template_Compiled](://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0) Friday (the 21st). The comments regarded multiple tabs, but you can see them all by clicking the cartoon speech bubble icon in the upper right and selecting 'All Sheets' in the pull down menu that appears slightly below the speech bubble icon.

The comments are mostly regarding the use of patterns like {float} and the semantics of the definition column vs. guidance. They're just meant as starting points for collaboratively revising `Soil-NMDC-Template_Compiled`. We could bring other people into this discussion.

**Comment by mslarae13** [comment]
I think it's safe to say this file is deprecated & this can be closed.

**Comment by pkalita-lbl** [comment]
Google Sheets no longer used in pipeline. Closing.
