### ISSUE TITLE
yet another 'Failed to map'

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#79]
Failed to map:

    The template for the loaded file has a configuration error:
    MIXS:investigation field
    This is a field that has no parent, or a section that has no fields.

**Comment by turbomam** [comment]
see also #31 and cascaded issues from there

**Comment by turbomam** [comment]
I think it required > 1 columns per section, not > 0 columns per section

**Comment by turbomam** [comment]
Terms from the `MIXS:investigation field` section appeared as  a result of fixing a SQL statement in `use_modular_gd.py`: 

tasks->mixs->query->where

from `disposition = 'use as-is' or disposition = 'borrowed as-is'` to `disposition = 'use as-is' or disposition = 'borrowed'`

which added the section `MIXS:investigation field` with just one column MIXS:0000008 `experimental factor`

**Comment by turbomam** [comment]
Adding

Ontology ID | label | parent class | description | guidance | datatype | pattern | requirement | examples | source | capitalize | data status | max value | min value | EXPORT_dev
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | placeholder | MIXS:investigation field |   |   |   |   |   |   |   |   |   |   |   |  

at the bottom of `target/data.tsv` and running `make -o target/data.tsv docs/template/dev/data.tsv` **eliminates the error and confirms at least two columns are required for each section**

@sujaypatil96

**Comment by sujaypatil96** [comment]
Find more information about a possible fix here: https://github.com/cidgoh/DataHarmonizer/issues/253
