### ISSUE TITLE
Will need something like change sheets for SNTC

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#88]
Soon we will not be able to make changes to the schema specified by SNTC without reshaping the data in mongodb to comply with SNTC. This will have to be a related, documented, traceable process

**Comment by pkalita-lbl** [comment]
Closing in preparation of archiving this fork. Use the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer) for development.
