### ISSUE TITLE
enum next steps

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#89]
- [x] get enums from `enums_long` not `enumerations`
- [x] filter by env_package
- [x] use term ids for PV meaning if provided
- [x] add gold path enums see also #85 
- [x] add environmental triad enums
    - getting left space padded values into Google Sheets may be tricky
    - getting repeated, indented PVs into LinkML may be tricky 
    - [x] broad
    - [x] local
    - [x] medium

**Comment by pkalita-lbl** [comment]
All tasks appear to be done. Closing.
