### ISSUE TITLE
add enum meanings back in

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#9]

**Comment by turbomam** [comment]
We will probably want to make this a free standing curation step in the future.

Several steps like this in the Makefile. How to template/generalize them?

	poetry run enum_annotator \
		--modelfile target/soil_biosample_modular.yaml \
		--requested_enum_name fao_class_enum \
		--ontology_string ENVO \
		--max_cosine 0.1  > target/temp1.yaml

**Comment by pkalita-lbl** [comment]
This sounds like a good thing to take into consideration when looking at https://github.com/microbiomedata/issues/issues/80. Closing.
