### ISSUE TITLE
hident requires robot

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#94]
https://github.com/turbomam/hident

**Comment by turbomam** [comment]
for converting ontologies into subClassOf and label files

**Comment by pkalita-lbl** [comment]
I believe hident has been superseded by [code](https://github.com/microbiomedata/submission-schema/blob/213cc49e528f799a03a1593f92e77dd7ec5d10a7/src/nmdc_submission_schema/datamodel/oak_tree_to_pv_list.py) in the `submission-schema` repo that uses OAK instead of ROBOT.
