### ISSUE TITLE
manually entered values in pulldown column do not validate

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#95]
even if they match the pattern

@dehays I can demonstrate this in real time or put together a documented case

**Comment by ssarrafan** [comment]
@turbomam removed David from assignees. Would you like to discuss this with someone else?

**Comment by pkalita-lbl** [comment]
I believe this should be working now that DataHarmonizer's validation code has been [refactored](https://github.com/cidgoh/DataHarmonizer/pull/420). If not please open an issue in the [main DataHarmonizer repo](https://github.com/cidgoh/DataHarmonizer).
